// Plain-JS copy of src/data/menu.ts with prices in CENTS (authoritative for the DB).
// The owner's printed menu. Keep in sync with src/data/menu.ts.
// `image` is optional; admin-uploaded images on existing items are preserved
// by sync-menu.js when this field is absent.
export const MENU = [
  {
    id: "breakfast",
    label: "Breakfast Favorites",
    note: "Served w/ hashbrowns and toast. Cooked to order.",
    items: [
      { name: "Baked Ham & Eggs", price_cents: 1135, image: "/photos/breakfast-ham-egg.webp" },
      { name: "Bacon & Eggs", price_cents: 1075, tag: "popular", image: "/photos/breakfast-bacon-eggs.webp" },
      { name: "Sausage & Eggs", price_cents: 1075, image: "/photos/breakfast-sausage-egg.webp" },
      { name: "Patties & Eggs", price_cents: 1120, image: "/photos/patties-eggs.webp" },
      { name: "Pork Chop & Eggs", price_cents: 1350, image: "/photos/pork-chop-eggs.webp" },
      { name: "2 Fried Eggs", price_cents: 925, image: "/photos/breakfast-fried-eggs.webp" },
      { name: "Strip Steak & Eggs", price_cents: 1650, image: "/photos/steak-eggs.webp" },
      { name: "Corned Beef Hash & Eggs", price_cents: 1375, image: "/photos/skillet-corned-beef.webp" },
    ],
  },
  {
    id: "breakfast-sandwiches",
    label: "Breakfast Sandwiches",
    note: "On French bread add $1.65.",
    items: [
      { name: "Bacon & Egg", price_cents: 710, image: "/photos/breakfast-bacon-egg.webp" },
      { name: "Sausage & Egg", price_cents: 710, image: "/photos/breakfast-sausage-egg.webp" },
      { name: "Ham & Egg", price_cents: 810, image: "/photos/breakfast-ham-egg.webp" },
      { name: "Ham & Cheese", price_cents: 810, image: "/photos/breakfast-ham-cheese.webp" },
      { name: "Fried Eggs", price_cents: 555, image: "/photos/breakfast-fried-eggs.webp" },
    ],
  },
  {
    id: "skillets",
    label: "Tasty Skillets",
    note: "Served w/ 2 eggs & toast.",
    items: [
      { name: "Meat Lover's", price_cents: 1420, description: "Sausage, bacon, ham & cheese", image: "/photos/skillet-meat-lovers.webp" },
      { name: "Hobo", price_cents: 1175, description: "Onion, green pepper & cheese", image: "/photos/skillet-hobo.webp" },
      { name: "Gypsy", price_cents: 1420, description: "Onion, pepper, mushroom, ham & cheese", image: "/photos/skillet-gypsy.webp" },
      { name: "Mexican", price_cents: 1395, description: "Chorizo, onion, green pepper & cheese", image: "/photos/skillet-mexican.webp" },
      { name: "Steak", price_cents: 1525, description: "Onion, green pepper, mushroom & cheese", image: "/photos/skillet-steak.webp" },
      { name: "Corned Beef", price_cents: 1425, description: "Onion, green pepper & cheese", image: "/photos/skillet-corned-beef.webp" },
      { name: "California Skillet", price_cents: 1435, description: "Chicken, broccoli, Swiss cheese & avocado", image: "/photos/skillet-california.webp" },
      { name: "Veggie Skillet", price_cents: 1290, description: "Onion, tomato, peppers, broccoli, mushroom, spinach & cheese", image: "/photos/skillet-veggie.webp" },
    ],
  },
  {
    id: "omelettes",
    label: "Signature Omelettes",
    note: "Served w/ hashbrowns and toast.",
    items: [
      { name: "Build Your Own Up To 4 Items", price_cents: 1450, description: "Additional items $2.50", tag: "new", image: "/photos/omelette-byo.webp" },
      { name: "Popeye", price_cents: 1240, description: "Spinach and feta cheese", image: "/photos/omelette-popeye.webp" },
      { name: "Cheese", price_cents: 1050, image: "/photos/omelette-cheese.webp" },
      { name: "Ham & Cheese", price_cents: 1270, image: "/photos/omelette-ham-cheese.webp" },
      { name: "Denver", price_cents: 1270, description: "Green pepper, onion, ham, cheese", image: "/photos/omelette-denver.webp" },
      { name: "Garbage", price_cents: 1290, description: "Green pepper, onion, tomato, ham, mushrooms and cheese", image: "/photos/omelette-garbage.webp" },
      { name: "Chorizo", price_cents: 1325, description: "Chorizo and cheese", image: "/photos/omelette-chorizo.webp" },
      { name: "Chili & Cheese", price_cents: 1325, image: "/photos/omelette-chili-cheese.webp" },
      { name: "Southern", price_cents: 1325, description: "Ham, onion, Swiss cheese, topped w/ sausage gravy", image: "/photos/omelette-southern.webp" },
      { name: "Meat Lover's", price_cents: 1425, description: "Ham, sausage, bacon and cheese", image: "/photos/omelette-meat-lovers.webp" },
      { name: "Veggie", price_cents: 1325, description: "Onion, tomato, peppers, broccoli, mushroom, spinach & cheese", image: "/photos/omelette-veggie.webp" },
      {
        name: "Slinger",
        price_cents: 1650,
        description:
          "Hash browns, 2 burger patties, cheese, grilled onion, 2 eggs over easy, topped with our diner's tasty chili!",
        tag: "signature",
        image: "/photos/slinger.webp",
      },
    ],
  },
  {
    id: "chefs-creations",
    label: "Chef's Creations",
    items: [
      { name: "Buffalo Wings (8)", price_cents: 1100, image: "/photos/wings.webp" },
      { name: "Mozzarella Sticks", price_cents: 865, image: "/photos/mozzarella-sticks.webp" },
      { name: "Jalapeno Poppers", price_cents: 865, image: "/photos/jalapeno-poppers.webp" },
      { name: "Cuban Sandwich", price_cents: 940, tag: "new", image: "/photos/cubano.webp" },
      {
        name: "Biscuits & Gravy",
        price_cents: 990,
        description: "With 2 eggs $11.40 · with 2 eggs & sausage or bacon $13.15",
        image: "/photos/biscuits-gravy.webp",
      },
      { name: "Haystack", price_cents: 1470, image: "/photos/skillet-eggs.webp" },
      {
        name: "Diner Bites",
        price_cents: 1525,
        description: "Jalapeno poppers, mozzarella sticks, wings & onion rings",
        tag: "popular",
        image: "/photos/diner-bites.webp",
      },
      {
        name: "Chilaquiles",
        price_cents: 1150,
        description: "With steak $14.50 · with chicken $13.65 · with chorizo $13.25",
        image: "/photos/chilaquiles.webp",
      },
    ],
  },
  {
    id: "pancakes-waffles",
    label: "Pancakes & Waffles",
    items: [
      {
        name: "Pancakes (3)",
        price_cents: 925,
        description: "With bacon or sausage $11.25 · with ham $12.25",
        image: "/photos/pancakes-3.webp",
      },
      {
        name: "Short Stack",
        price_cents: 825,
        description: "With bacon or sausage $9.50 · with ham $9.50",
        image: "/photos/pancakes-short-stack.webp",
      },
      { name: "Choco Chip Pancakes (3)", price_cents: 1010, image: "/photos/pancakes-choco-chip.webp" },
      { name: "Choco Chip Short Stack", price_cents: 825, tag: "new", image: "/photos/pancakes-choco-short.webp" },
      { name: "Banana & Nutella Pancakes", price_cents: 1025, image: "/photos/pancakes-banana-nutella.webp" },
      { name: "Banana & Caramel Pancakes", price_cents: 1025, image: "/photos/pancakes-banana-caramel.webp" },
      { name: "Belgian Waffle", price_cents: 1075, image: "/photos/waffle-belgian.webp" },
      { name: "Banana & Nutella Waffle", price_cents: 1200, image: "/photos/waffle-banana-nutella.webp" },
      {
        name: "Alaskan Waffle",
        price_cents: 1265,
        description: "Comes with 2 scoops of ice cream, vanilla or strawberry",
        image: "/photos/waffle-alaskan.webp",
      },
    ],
  },
  {
    id: "french-toast",
    label: "French Toast",
    items: [
      {
        name: "French Toast",
        price_cents: 1025,
        description: "With bacon or sausage $11.75 · with ham $12.25",
        image: "/photos/french-toast.webp",
      },
    ],
  },
  {
    id: "sandwiches",
    label: "Sandwiches",
    items: [
      { name: "Beef Burger", price_cents: 560, image: "/photos/beef-burger.webp" },
      { name: "Double Burger", price_cents: 705, image: "/photos/double-burger.webp" },
      { name: "Cheese Burger", price_cents: 640, image: "/photos/cheeseburger.webp" },
      { name: "Cubano", price_cents: 940, tag: "new", image: "/photos/cubano.webp" },
      { name: "Double Cheese Burger", price_cents: 785, tag: "popular", image: "/photos/double-cheeseburger.webp" },
      { name: "Bacon Cheese Burger", price_cents: 775, image: "/photos/bacon-cheeseburger.webp" },
      { name: "Double Bacon Cheese Burger", price_cents: 920, image: "/photos/double-bacon-cheeseburger.webp" },
      { name: "Grilled Cheese", price_cents: 620, image: "/photos/grilled-cheese.webp" },
      { name: "Grilled Cheese & Bacon", price_cents: 775, image: "/photos/grilled-cheese-bacon.webp" },
      { name: "Grilled Cheese & Ham", price_cents: 820, tag: "new", image: "/photos/grilled-cheese-ham.webp" },
      { name: "Chicken Sand", price_cents: 920, image: "/photos/chicken-sand.webp" },
      { name: "Buffalo Chicken", price_cents: 995, tag: "new", image: "/photos/buffalo-chicken.webp" },
      { name: "Ribeye Sand", price_cents: 1165, image: "/photos/ribeye-sand.webp" },
      { name: "Strip Steak", price_cents: 1280, tag: "new", image: "/photos/strip-steak-sand.webp" },
      { name: "Pork Chop", price_cents: 1110, tag: "new", image: "/photos/pork-chop-sand.webp" },
      { name: "BLT Sand", price_cents: 810, tag: "new", image: "/photos/blt.webp" },
      { name: "Pulled Pork", price_cents: 820, tag: "new", image: "/photos/pulled-pork.webp" },
      { name: "Patty Melt", price_cents: 845, tag: "new", image: "/photos/patty-melt.webp" },
      { name: "Catfish Sand", price_cents: 945, tag: "new", image: "/photos/catfish-sand.webp" },
    ],
  },
  {
    id: "burritos",
    label: "Diner Burritos",
    items: [
      {
        name: "Breakfast Burrito",
        price_cents: 950,
        description: "Sausage, bacon, eggs, hash browns, crema, cheese & avocado",
        tag: "new",
        image: "/photos/burrito-breakfast.webp",
      },
      {
        name: "California Burrito",
        price_cents: 1075,
        description: "Steak or chicken, pico de gallo, fries, crema & avocado",
        tag: "new",
        image: "/photos/burrito-california.webp",
      },
      {
        name: "Veggie Burrito",
        price_cents: 1025,
        description: "All veggies, eggs, hash browns, cheese, crema & avocado",
        tag: "new",
        image: "/photos/burrito-veggie.webp",
      },
    ],
  },
  {
    id: "sides",
    label: "Side Orders",
    items: [
      { name: "Soup", price_cents: 400, description: "SM $4.00 · LG $4.50", image: "/photos/soup.webp" },
      { name: "Chili", price_cents: 425, description: "SM $4.25 · LG $5.50", image: "/photos/chili.webp" },
      { name: "Fries", price_cents: 425, image: "/photos/fries.webp" },
      { name: "Hashbrowns", price_cents: 425, image: "/photos/hashbrowns.webp" },
      { name: "Onion Rings", price_cents: 450, image: "/photos/onion-rings.webp" },
      { name: "Cheese Fries", price_cents: 545, image: "/photos/cheese-fries.webp" },
      { name: "Loaded Fries", price_cents: 875, image: "/photos/loaded-fries.webp" },
      { name: "BBQ Pulled Pork Fries", price_cents: 595, image: "/photos/bbq-fries.webp" },
      { name: "Ham", price_cents: 585, image: "/photos/side-ham.webp" },
      { name: "Sausage Links", price_cents: 505, image: "/photos/side-sausage.webp" },
      { name: "Bacon", price_cents: 505, image: "/photos/side-bacon.webp" },
      { name: "1 Egg", price_cents: 225, image: "/photos/breakfast-fried-eggs.webp" },
      { name: "Toast", price_cents: 305, image: "/photos/toast.webp" },
      { name: "Sausage Gravy", price_cents: 545, image: "/photos/biscuits-gravy.webp" },
      { name: "Corned Beef Hash", price_cents: 545, image: "/photos/skillet-corned-beef.webp" },
    ],
  },
  {
    id: "kids",
    label: "Kids Menu",
    items: [
      {
        name: "Mickey Mouse Pancake",
        price_cents: 750,
        description: "With bacon or sausage +$2.00",
        tag: "new",
        image: "/photos/mickey-pancake.webp",
      },
      { name: "Cheese Burger w/ Fries", price_cents: 825, tag: "new", image: "/photos/cheeseburger.webp" },
      { name: "Grilled Cheese w/ Fries", price_cents: 825, tag: "new", image: "/photos/grilled-cheese.webp" },
    ],
  },
  {
    id: "desserts",
    label: "Desserts",
    items: [
      { name: "Dessert of the Day", price_cents: 650, tag: "new", image: "/photos/dessert-of-the-day.webp" },
      { name: "Churros", price_cents: 730, tag: "new", image: "/photos/churros.webp" },
      { name: "Milkshake", price_cents: 625, image: "/photos/milkshake.webp" },
    ],
  },
  {
    id: "drinks",
    label: "Drinks",
    items: [
      { name: "Coffee", price_cents: 295, image: "/photos/coffee.webp" },
      {
        name: "Coffee To Go",
        price_cents: 295,
        description: "SM $2.95 · LG $3.20",
        image: "/photos/drink-coffee-to-go.webp",
      },
      {
        name: "Soft Drinks",
        price_cents: 300,
        description: "SM $3.00 · LG $3.25",
        image: "/photos/soda-coke.webp",
      },
      { name: "Juice", price_cents: 345, description: "SM $3.45 · LG $3.75", image: "/photos/drink-juice.webp" },
      { name: "Milk", price_cents: 215, description: "SM $2.15 · LG $3.15", image: "/photos/drink-milk.webp" },
      { name: "Choco Milk", price_cents: 350, image: "/photos/drink-choco-milk.webp" },
      { name: "Iced Coffee", price_cents: 395, image: "/photos/drink-iced-coffee.webp" },
      { name: "Hot Tea", price_cents: 275, image: "/photos/drink-hot-tea.webp" },
      { name: "Hot Cocoa", price_cents: 215, image: "/photos/drink-hot-cocoa.webp" },
      { name: "Lemonade", price_cents: 350, image: "/photos/drink-lemonade.webp" },
    ],
  },
];
