// Plain-JS copy of src/data/menu.ts with prices in CENTS (authoritative for the DB).
// The owner's printed menu. Keep in sync with src/data/menu.ts.
// `image` is optional; admin-uploaded images on existing items are preserved
// by sync-menu.js when this field is absent.
export const MENU = [
  {
    id: "breakfast",
    label: "Breakfast Favorites",
    note: "Served w/ hashbrowns and toast. Cooked to order.",
    items: [
      { name: "Baked Ham & Eggs", price_cents: 1135 },
      { name: "Bacon & Eggs", price_cents: 1075, tag: "popular" },
      { name: "Sausage & Eggs", price_cents: 1075 },
      { name: "Patties & Eggs", price_cents: 1120 },
      { name: "Pork Chop & Eggs", price_cents: 1350 },
      { name: "2 Fried Eggs", price_cents: 925 },
      { name: "Strip Steak & Eggs", price_cents: 1650 },
      { name: "Corned Beef Hash & Eggs", price_cents: 1375 },
    ],
  },
  {
    id: "breakfast-sandwiches",
    label: "Breakfast Sandwiches",
    note: "On French bread add $1.65.",
    items: [
      { name: "Bacon & Egg", price_cents: 710, image: "/photos/breakfast-bacon-egg.jpg" },
      { name: "Sausage & Egg", price_cents: 710, image: "/photos/breakfast-sausage-egg.jpg" },
      { name: "Ham & Egg", price_cents: 810, image: "/photos/breakfast-ham-egg.jpg" },
      { name: "Ham & Cheese", price_cents: 810, image: "/photos/breakfast-ham-cheese.jpg" },
      { name: "Fried Eggs", price_cents: 555, image: "/photos/breakfast-fried-eggs.jpg" },
    ],
  },
  {
    id: "skillets",
    label: "Tasty Skillets",
    note: "Served w/ 2 eggs & toast.",
    items: [
      { name: "Meat Lover's", price_cents: 1420, description: "Sausage, bacon, ham & cheese", image: "/photos/skillet-meat-lovers.jpg" },
      { name: "Hobo", price_cents: 1175, description: "Onion, green pepper & cheese", image: "/photos/skillet-hobo.jpg" },
      { name: "Gypsy", price_cents: 1420, description: "Onion, pepper, mushroom, ham & cheese", image: "/photos/skillet-gypsy.jpg" },
      { name: "Mexican", price_cents: 1395, description: "Chorizo, onion, green pepper & cheese", image: "/photos/skillet-mexican.jpg" },
      { name: "Steak", price_cents: 1525, description: "Onion, green pepper, mushroom & cheese", image: "/photos/skillet-steak.jpg" },
      { name: "Corned Beef", price_cents: 1425, description: "Onion, green pepper & cheese", image: "/photos/skillet-corned-beef.jpg" },
      { name: "California", price_cents: 1435, description: "Chicken, broccoli, Swiss cheese & avocado", image: "/photos/skillet-california.jpg" },
      { name: "Veggie", price_cents: 1290, description: "Onion, tomato, peppers, broccoli, mushroom, spinach & cheese", image: "/photos/skillet-veggie.jpg" },
    ],
  },
  {
    id: "omelettes",
    label: "Signature Omelettes",
    note: "Served w/ hashbrowns and toast.",
    items: [
      { name: "Build Your Own", price_cents: 1450, description: "Up to 4 items — additional items $2.50", tag: "new", image: "/photos/omelette-byo.jpg" },
      { name: "Popeye", price_cents: 1240, description: "Spinach and feta cheese", image: "/photos/omelette-popeye.jpg" },
      { name: "Cheese", price_cents: 1050, image: "/photos/omelette-cheese.jpg" },
      { name: "Ham & Cheese", price_cents: 1270, image: "/photos/omelette-ham-cheese.jpg" },
      { name: "Denver", price_cents: 1270, description: "Green pepper, onion, ham, cheese", image: "/photos/omelette-denver.jpg" },
      { name: "Garbage", price_cents: 1290, description: "Green pepper, onion, tomato, ham, mushrooms and cheese", image: "/photos/omelette-garbage.jpg" },
      { name: "Chorizo", price_cents: 1325, description: "Chorizo and cheese", image: "/photos/omelette-chorizo.jpg" },
      { name: "Chili & Cheese", price_cents: 1325, image: "/photos/omelette-chili-cheese.jpg" },
      { name: "Southern", price_cents: 1325, description: "Ham, onion, Swiss cheese, topped w/ sausage gravy", image: "/photos/omelette-southern.jpg" },
      { name: "Meat Lover's", price_cents: 1425, description: "Ham, sausage, bacon and cheese", image: "/photos/omelette-meat-lovers.jpg" },
      { name: "Veggie", price_cents: 1325, description: "Onion, tomato, peppers, broccoli, mushroom, spinach & cheese", image: "/photos/omelette-veggie.jpg" },
      {
        name: "The Slinger",
        price_cents: 1650,
        description:
          "Hash browns, 2 burger patties, cheese, grilled onion, 2 eggs over easy, topped with our diner's tasty chili!",
        tag: "signature",
        image: "/photos/slinger.jpg",
      },
    ],
  },
  {
    id: "chefs-creations",
    label: "Chef's Creations",
    items: [
      { name: "Buffalo Wings (8)", price_cents: 1100, image: "/photos/wings.jpg" },
      { name: "Mozzarella Sticks", price_cents: 865, image: "/photos/mozzarella-sticks.jpg" },
      { name: "Jalapeno Poppers", price_cents: 865, image: "/photos/jalapeno-poppers.jpg" },
      { name: "Cuban Sandwich", price_cents: 940, tag: "new", image: "/photos/cubano.jpg" },
      {
        name: "Biscuits & Gravy",
        price_cents: 990,
        description: "With 2 eggs $11.40 · with 2 eggs & sausage or bacon $13.15",
      },
      { name: "Haystack", price_cents: 1470, image: "/photos/skillet-eggs.jpg" },
      {
        name: "Diner Bites",
        price_cents: 1525,
        description: "Jalapeno poppers, mozzarella sticks, wings & onion rings",
        tag: "popular",
        image: "/photos/diner-bites.jpg",
      },
      {
        name: "Chilaquiles",
        price_cents: 1150,
        description: "With steak $14.50 · with chicken $13.65 · with chorizo $13.25",
        image: "/photos/chilaquiles.jpg",
      },
    ],
  },
  {
    id: "pancakes-waffles",
    label: "Pancakes & Waffles",
    items: [
      {
        name: "Pancakes (3)",
        price_cents: 925,
        description: "With bacon or sausage $11.25 · with ham $12.25",
        image: "/photos/pancakes-3.jpg",
      },
      {
        name: "Short Stack",
        price_cents: 825,
        description: "With bacon or sausage $9.50 · with ham $9.50",
        image: "/photos/pancakes-short-stack.jpg",
      },
      { name: "Choco Chip Pancakes (3)", price_cents: 1010, image: "/photos/pancakes-choco-chip.jpg" },
      { name: "Choco Chip Short Stack", price_cents: 825, tag: "new", image: "/photos/pancakes-choco-short.jpg" },
      { name: "Banana & Nutella Pancakes", price_cents: 1025, image: "/photos/pancakes-banana-nutella.jpg" },
      { name: "Banana & Caramel Pancakes", price_cents: 1025, image: "/photos/pancakes-banana-caramel.jpg" },
      { name: "Belgian Waffle", price_cents: 1075, image: "/photos/waffle-belgian.jpg" },
      { name: "Banana & Nutella Waffle", price_cents: 1200, image: "/photos/waffle-banana-nutella.jpg" },
      {
        name: "Alaskan Waffle",
        price_cents: 1265,
        description: "Comes with 2 scoops of ice cream, vanilla or strawberry",
        image: "/photos/waffle-alaskan.jpg",
      },
    ],
  },
  {
    id: "french-toast",
    label: "French Toast",
    items: [
      {
        name: "French Toast",
        price_cents: 1025,
        description: "With bacon or sausage $11.75 · with ham $12.25",
        image: "/photos/french-toast.jpg",
      },
    ],
  },
  {
    id: "sandwiches",
    label: "Sandwiches",
    items: [
      { name: "Beef Burger", price_cents: 560 },
      { name: "Double Burger", price_cents: 705 },
      { name: "Cheese Burger", price_cents: 640, image: "/photos/cheeseburger.jpg" },
      { name: "Cubano", price_cents: 940, tag: "new", image: "/photos/cubano.jpg" },
      { name: "Double Cheese Burger", price_cents: 785, tag: "popular" },
      { name: "Bacon Cheese Burger", price_cents: 775 },
      { name: "Double Bacon Cheese Burger", price_cents: 920 },
      { name: "Grilled Cheese", price_cents: 620 },
      { name: "Grilled Cheese & Bacon", price_cents: 775 },
      { name: "Grilled Cheese & Ham", price_cents: 820, tag: "new" },
      { name: "Chicken Sand", price_cents: 920 },
      { name: "Buffalo Chicken", price_cents: 995, tag: "new" },
      { name: "Ribeye Sand", price_cents: 1165 },
      { name: "Strip Steak", price_cents: 1280, tag: "new" },
      { name: "Pork Chop", price_cents: 1110, tag: "new" },
      { name: "BLT Sand", price_cents: 810, tag: "new" },
      { name: "Pulled Pork", price_cents: 820, tag: "new" },
      { name: "Patty Melt", price_cents: 845, tag: "new", image: "/photos/melt.jpg" },
      { name: "Catfish Sand", price_cents: 945, tag: "new" },
    ],
  },
  {
    id: "burritos",
    label: "Diner Burritos",
    items: [
      {
        name: "Breakfast Burrito",
        price_cents: 950,
        description: "Sausage, bacon, eggs, hash browns, crema, cheese & avocado",
        tag: "new",
        image: "/photos/burrito-breakfast.jpg",
      },
      {
        name: "California Burrito",
        price_cents: 1075,
        description: "Steak or chicken, pico de gallo, fries, crema & avocado",
        tag: "new",
        image: "/photos/burrito-california.jpg",
      },
      {
        name: "Veggie Burrito",
        price_cents: 1025,
        description: "All veggies, eggs, hash browns, cheese, crema & avocado",
        tag: "new",
        image: "/photos/burrito-veggie.jpg",
      },
    ],
  },
  {
    id: "sides",
    label: "Side Orders",
    items: [
      { name: "Soup", price_cents: 400, description: "SM $4.00 · LG $4.50" },
      { name: "Chili", price_cents: 425, description: "SM $4.25 · LG $5.50" },
      { name: "Fries", price_cents: 425 },
      { name: "Hashbrowns", price_cents: 425 },
      { name: "Onion Rings", price_cents: 450, image: "/photos/onion-rings.jpg" },
      { name: "Cheese Fries", price_cents: 545 },
      { name: "Loaded Fries", price_cents: 875 },
      { name: "BBQ Pulled Pork Fries", price_cents: 595 },
      { name: "Ham", price_cents: 585 },
      { name: "Sausage Links", price_cents: 505 },
      { name: "Bacon", price_cents: 505 },
      { name: "1 Egg", price_cents: 225 },
      { name: "Toast", price_cents: 305 },
      { name: "Sausage Gravy", price_cents: 545 },
      { name: "Corned Beef Hash", price_cents: 545 },
    ],
  },
  {
    id: "kids",
    label: "Kids Menu",
    items: [
      {
        name: "Mickey Mouse Pancake",
        price_cents: 750,
        description: "With bacon or sausage +$2.00",
        tag: "new",
        image: "/photos/mickey-pancake.jpg",
      },
      { name: "Cheese Burger w/ Fries", price_cents: 825, tag: "new" },
      { name: "Grilled Cheese w/ Fries", price_cents: 825, tag: "new" },
    ],
  },
  {
    id: "desserts",
    label: "Desserts",
    items: [
      { name: "Dessert of the Day", price_cents: 650, tag: "new", image: "/photos/dessert-of-the-day.jpg" },
      { name: "Churros", price_cents: 730, tag: "new", image: "/photos/churros.jpg" },
    ],
  },
  {
    id: "drinks",
    label: "Drinks",
    items: [
      { name: "Coffee", price_cents: 295, image: "/photos/coffee.jpg" },
      {
        name: "Coffee To Go",
        price_cents: 295,
        description: "SM $2.95 · LG $3.20",
        image: "/photos/drink-coffee-to-go.jpg",
      },
      { name: "Coke", price_cents: 300, description: "SM $3.00 · LG $3.25", image: "/photos/soda-coke.jpg" },
      { name: "Diet Coke", price_cents: 300, description: "SM $3.00 · LG $3.25", image: "/photos/soda-diet-coke.jpg" },
      { name: "Sprite", price_cents: 300, description: "SM $3.00 · LG $3.25", image: "/photos/soda-sprite.jpg" },
      { name: "Root Beer", price_cents: 300, description: "SM $3.00 · LG $3.25", image: "/photos/soda-root-beer.jpg" },
      { name: "Ginger Ale", price_cents: 300, description: "SM $3.00 · LG $3.25", image: "/photos/soda-ginger-ale.jpg" },
      { name: "Juice", price_cents: 345, description: "SM $3.45 · LG $3.75", image: "/photos/drink-juice.jpg" },
      { name: "Milk", price_cents: 215, description: "SM $2.15 · LG $3.15", image: "/photos/drink-milk.jpg" },
      { name: "Choco Milk", price_cents: 350, image: "/photos/drink-choco-milk.jpg" },
      { name: "Iced Coffee", price_cents: 395, image: "/photos/drink-iced-coffee.jpg" },
      { name: "Hot Tea", price_cents: 275, image: "/photos/drink-hot-tea.jpg" },
      { name: "Hot Cocoa", price_cents: 215, image: "/photos/drink-hot-cocoa.jpg" },
      { name: "Lemonade", price_cents: 350, image: "/photos/drink-lemonade.jpg" },
      { name: "Milkshake", price_cents: 625, image: "/photos/milkshake.jpg" },
    ],
  },
];
