// Plain-JS copy of src/data/menu.ts with prices in CENTS (authoritative for the DB).
// The owner's printed menu (May 2026). Keep in sync with src/data/menu.ts.
// `image` is optional; admin-uploaded images on existing items are preserved
// by sync-menu.js when this field is absent.
export const MENU = [
  {
    id: "breakfast",
    label: "Breakfast Favorites",
    note: "Served with hashbrowns and toast. Cooked to order.",
    items: [
      { name: "Baked Ham & Eggs", price_cents: 1135 },
      { name: "Bacon & Eggs", price_cents: 1075, tag: "popular" },
      { name: "Sausage & Eggs", price_cents: 1075 },
      { name: "Patties & Eggs", price_cents: 1120 },
      { name: "Pork Chop & Eggs", price_cents: 1350 },
      { name: "2 Fried Eggs", price_cents: 925 },
      { name: "Strip Steak & Eggs", price_cents: 1650 },
      { name: "Corned Beef Hash & Eggs", price_cents: 1375 },
    ],
  },
  {
    id: "breakfast-sandwiches",
    label: "Breakfast Sandwiches",
    note: "On French bread add $1.65.",
    items: [
      { name: "Bacon & Egg", price_cents: 710 },
      { name: "Sausage & Egg", price_cents: 710 },
      { name: "Ham & Egg", price_cents: 810 },
      { name: "Ham & Cheese", price_cents: 810 },
      { name: "Fried Egg", price_cents: 555 },
    ],
  },
  {
    id: "skillets",
    label: "Tasty Skillets",
    note: "Served with 2 eggs & toast.",
    items: [
      { name: "Meat Lover's", price_cents: 1420, description: "Sausage, bacon, ham & cheese", image: "/photos/skillet-eggs.jpg" },
      { name: "Hobo", price_cents: 1175, description: "Onion, green pepper & cheese", image: "/photos/skillet-eggs.jpg" },
      { name: "Gypsy", price_cents: 1420, description: "Onion, pepper, mushroom, ham & cheese", image: "/photos/skillet-eggs.jpg" },
      { name: "Mexican", price_cents: 1395, description: "Chorizo, onion, green pepper & cheese", image: "/photos/skillet-eggs.jpg" },
      { name: "Steak", price_cents: 1525, description: "Onion, green pepper, mushroom & cheese", image: "/photos/skillet-eggs.jpg" },
      { name: "Corned Beef", price_cents: 1425, description: "Onion, green pepper & cheese", image: "/photos/skillet-eggs.jpg" },
      { name: "California", price_cents: 1435, description: "Chicken, broccoli, Swiss cheese & avocado", image: "/photos/skillet-eggs.jpg" },
      { name: "Veggie", price_cents: 1290, description: "Onion, tomato, peppers, broccoli, mushroom, spinach & cheese", image: "/photos/skillet-eggs.jpg" },
    ],
  },
  {
    id: "omelettes",
    label: "Signature Omelettes",
    note: "Served with hashbrowns and toast. Build your own up to 4 items $14.50 — additional items $2.50.",
    items: [
      { name: "Build Your Own", price_cents: 1450, description: "Up to 4 items — additional items $2.50", tag: "new" },
      { name: "Popeye", price_cents: 1240, description: "Spinach and feta cheese" },
      { name: "Cheese", price_cents: 1050 },
      { name: "Ham & Cheese", price_cents: 1270 },
      { name: "Denver", price_cents: 1270, description: "Green pepper, onion, ham, cheese" },
      { name: "Garbage", price_cents: 1290, description: "Green pepper, onion, tomato, ham, mushrooms and cheese" },
      { name: "Chorizo", price_cents: 1325, description: "Chorizo and cheese" },
      { name: "Chili & Cheese", price_cents: 1325 },
      { name: "Southern", price_cents: 1325, description: "Ham, onion, Swiss cheese, topped with sausage gravy" },
      { name: "Meat Lover's", price_cents: 1425, description: "Ham, sausage, bacon and cheese" },
      { name: "Veggie", price_cents: 1325, description: "Onion, tomato, peppers, broccoli, mushroom, spinach & cheese" },
    ],
  },
  {
    id: "chefs-creations",
    label: "Chef's Creations",
    note: "The plates people cross town for.",
    items: [
      {
        name: "The Slinger",
        price_cents: 1650,
        description: "Hash browns, 2 burger patties, cheese, grilled onion, 2 eggs over easy, topped with our diner's tasty chili!",
        tag: "signature",
        image: "/photos/slinger.jpg",
      },
      { name: "Haystack", price_cents: 1470, image: "/photos/skillet-eggs.jpg" },
      { name: "Biscuits & Gravy", price_cents: 990, description: "With 2 eggs $11.40 · with 2 eggs & sausage or bacon $13.15" },
      { name: "Chilaquiles", price_cents: 1150, description: "With chorizo $13.25 · chicken $13.65 · steak $14.50", image: "/photos/chilaquiles.jpg" },
      { name: "Cuban Sandwich", price_cents: 940, tag: "new", image: "/photos/cubano.jpg" },
      { name: "Buffalo Wings (8)", price_cents: 1100, image: "/photos/wings.jpg" },
      { name: "Mozzarella Sticks", price_cents: 865 },
      { name: "Jalapeno Poppers", price_cents: 865 },
      { name: "Diner Bites", price_cents: 1525, description: "Jalapeno poppers, mozzarella sticks, wings & onion rings", tag: "popular" },
    ],
  },
  {
    id: "griddle",
    label: "Pancakes, Waffles & French Toast",
    note: "All day, every day.",
    items: [
      { name: "Pancakes (3)", price_cents: 925, description: "With bacon or sausage $11.25 · with ham $12.25", image: "/photos/pancakes.jpg" },
      { name: "Short Stack", price_cents: 825, description: "With bacon, sausage or ham $9.50" },
      { name: "Choco Chip Pancakes (3)", price_cents: 1010 },
      { name: "Choco Chip Short Stack", price_cents: 825, tag: "new" },
      { name: "Banana & Nutella Pancakes", price_cents: 1025 },
      { name: "Banana & Caramel Pancakes", price_cents: 1025 },
      { name: "French Toast", price_cents: 1025, description: "With bacon or sausage $11.75 · with ham $12.25", image: "/photos/french-toast.jpg" },
      { name: "Belgian Waffle", price_cents: 1075, image: "/photos/waffle.jpg" },
      { name: "Banana & Nutella Waffle", price_cents: 1200 },
      { name: "Alaskan Waffle", price_cents: 1265, description: "Comes with 2 scoops of ice cream, vanilla or strawberry", image: "/photos/alaskan-waffle.jpg" },
    ],
  },
  {
    id: "sandwiches",
    label: "Sandwiches",
    note: "On French bread add $1.65.",
    items: [
      { name: "Beef Burger", price_cents: 560 },
      { name: "Double Burger", price_cents: 705 },
      { name: "Cheese Burger", price_cents: 640, image: "/photos/burger-shake.jpg" },
      { name: "Double Cheese Burger", price_cents: 785, tag: "popular" },
      { name: "Bacon Cheese Burger", price_cents: 775 },
      { name: "Double Bacon Cheese Burger", price_cents: 920 },
      { name: "Cubano", price_cents: 940, tag: "new", image: "/photos/cubano.jpg" },
      { name: "Grilled Cheese", price_cents: 620 },
      { name: "Grilled Cheese & Bacon", price_cents: 775 },
      { name: "Grilled Cheese & Ham", price_cents: 820, tag: "new" },
      { name: "Chicken Sand", price_cents: 920 },
      { name: "Buffalo Chicken", price_cents: 995, tag: "new" },
      { name: "Ribeye Sand", price_cents: 1165 },
      { name: "Strip Steak", price_cents: 1280, tag: "new" },
      { name: "Pork Chop", price_cents: 1110, tag: "new" },
      { name: "BLT Sand", price_cents: 810, tag: "new" },
      { name: "Pulled Pork", price_cents: 820, tag: "new" },
      { name: "Patty Melt", price_cents: 845, tag: "new", image: "/photos/melt.jpg" },
      { name: "Catfish Sand", price_cents: 945, tag: "new" },
    ],
  },
  {
    id: "burritos",
    label: "Diner Burritos",
    note: "Wrapped and griddled.",
    items: [
      { name: "Breakfast Burrito", price_cents: 950, description: "Sausage, bacon, eggs, hash browns, crema, cheese & avocado", tag: "new", image: "/photos/burrito.jpg" },
      { name: "California Burrito", price_cents: 1075, description: "Steak or chicken, pico de gallo, fries, crema & avocado", tag: "new", image: "/photos/burrito.jpg" },
      { name: "Veggie Burrito", price_cents: 1025, description: "All veggies, eggs, hash browns, cheese, crema & avocado", tag: "new", image: "/photos/burrito.jpg" },
    ],
  },
  {
    id: "sides",
    label: "Side Orders",
    items: [
      { name: "Soup", price_cents: 400, description: "Large $4.50" },
      { name: "Chili", price_cents: 425, description: "Large $5.50" },
      { name: "Fries", price_cents: 425 },
      { name: "Hashbrowns", price_cents: 425 },
      { name: "Onion Rings", price_cents: 450, image: "/photos/onion-rings.jpg" },
      { name: "Cheese Fries", price_cents: 545 },
      { name: "Loaded Fries", price_cents: 875 },
      { name: "BBQ Pulled Pork Fries", price_cents: 595 },
      { name: "Ham", price_cents: 585 },
      { name: "Sausage Links", price_cents: 505 },
      { name: "Bacon", price_cents: 505 },
      { name: "1 Egg", price_cents: 225 },
      { name: "Toast", price_cents: 305 },
      { name: "Sausage Gravy", price_cents: 545 },
      { name: "Corned Beef Hash", price_cents: 545 },
    ],
  },
  {
    id: "kids",
    label: "Kids Menu",
    items: [
      { name: "Mickey Mouse Pancake", price_cents: 750, description: "With bacon or sausage +$2.00", tag: "new", image: "/photos/mickey-pancake.jpg" },
      { name: "Cheese Burger w/ Fries", price_cents: 825, tag: "new" },
      { name: "Grilled Cheese w/ Fries", price_cents: 825, tag: "new" },
    ],
  },
  {
    id: "desserts",
    label: "Desserts",
    items: [
      { name: "Dessert of the Day", price_cents: 650, tag: "new" },
      { name: "Churros", price_cents: 730, tag: "new", image: "/photos/churros.jpg" },
    ],
  },
  {
    id: "drinks",
    label: "Drinks",
    items: [
      { name: "Coffee", price_cents: 295, image: "/photos/coffee.jpg" },
      { name: "Coffee To Go", price_cents: 295, description: "Large $3.20" },
      { name: "Soft Drinks", price_cents: 300, description: "Large $3.25" },
      { name: "Juice", price_cents: 345, description: "Large $3.75" },
      { name: "Milk", price_cents: 215, description: "Large $3.15" },
      { name: "Choco Milk", price_cents: 350 },
      { name: "Iced Coffee", price_cents: 395, image: "/photos/milkshake.jpg" },
      { name: "Hot Tea", price_cents: 275 },
      { name: "Hot Cocoa", price_cents: 215 },
      { name: "Lemonade", price_cents: 350 },
    ],
  },
];
